name: number_to_text_converter
description: A library to convert a number to its text representation as per the International or Indian Numbering System
version: 2.0.0
homepage: https://github.com/ShoutOutSoftware/NumberToTextConverter-Dart

environment:
  sdk: ">=3.0.5 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  pedantic: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter